# Check offsets

In [1]:
# imports
import os 
import numpy as np

from profiler.loading.pymatreader import pymatreader

import arcterx_utils

# Load

In [2]:
ctd_file = os.path.join(os.getenv('OS_DATA'), 'ARCTERX', '2025_IOP' ,'gliders', 
                        'ctd.mat')

In [3]:
ctd = pymatreader.read_mat(ctd_file, verify_compressed_data_integrity=True)

In [4]:
ctd['ctd']['dist'].shape

(2405,)

In [5]:
ctd['ctd']['dist'][0:10], ctd['ctd']['offset'][0:10]

(array([37.30417849, 36.73709287, 34.91054059, 33.7307837 , 33.13634669,
        32.20796216, 31.96232057, 32.15925063, 32.06990273, 29.84662496]),
 array([ 7.9956396,  7.2841938,  6.3571752,  5.6148936,  4.5742548,
         3.3769368,  1.9804362,  0.3741966, -1.6281858, -4.7542692]))

# Mine

In [6]:
profilers, Sn_dict, gPairs, rbins = arcterx_utils.calc_structure(
        'ARCTERX-Leg2', 'duLduLduL', ['Spray', 'Seaglider'], 9, 7.)

Loading Sprays
calc_dist_offset: theta=1.5707963267948966 rad, 90.0 deg
calc_dist_offset: theta=1.5707963267948966 rad, 90.0 deg
Loading Seagliders
Loading:  /home/xavier/Projects/Oceanography/data/ARCTERX/2025_IOP/gliders/Seagliders/sg528.mat
calc_dist_offset: theta=1.5707963267948966 rad, 90.0 deg
Loading:  /home/xavier/Projects/Oceanography/data/ARCTERX/2025_IOP/gliders/Seagliders/sg171.mat
calc_dist_offset: theta=1.5707963267948966 rad, 90.0 deg
Loading:  /home/xavier/Projects/Oceanography/data/ARCTERX/2025_IOP/gliders/Seagliders/sg196.mat
calc_dist_offset: theta=1.5707963267948966 rad, 90.0 deg
Using lonendpts: (129.9167, 129.9167)
Using latendpts: (20.3332, 20.3334)
calc_dist_offset: theta=1.5707963267948966 rad, 90.0 deg
calc_dist_offset: theta=1.5707963267948966 rad, 90.0 deg
calc_dist_offset: theta=1.5707963267948966 rad, 90.0 deg
calc_dist_offset: theta=1.5707963267948966 rad, 90.0 deg
calc_dist_offset: theta=1.5707963267948966 rad, 90.0 deg


In [15]:
lat_box=20.3333 
lon_box=129.9167

In [16]:
(20.40-20.333)*100

6.700000000000017

In [18]:
profilers[0].distE[2:10],profilers[0].distN[2:10]

(array([37.30417849, 36.73709287, 34.91054059, 33.7307837 , 33.13634669,
        32.20796216, 31.96232057, 32.15925063]),
 array([8.0067516, 7.2953058, 6.3682872, 5.6260056, 4.5853668, 3.3880488,
        1.9915482, 0.3853086]))

In [8]:
ctd['ctd']['dist'][0:8], ctd['ctd']['offset'][0:8]

(array([37.30417849, 36.73709287, 34.91054059, 33.7307837 , 33.13634669,
        32.20796216, 31.96232057, 32.15925063]),
 array([7.9956396, 7.2841938, 6.3571752, 5.6148936, 4.5742548, 3.3769368,
        1.9804362, 0.3741966]))

In [9]:
ctd['ctd']['lon'][0:10], ctd['ctd']['lat'][0:10]

(array([130.27472  , 130.2692775, 130.2517475, 130.240425 , 130.23472  ,
        130.22581  , 130.2234525, 130.2253425, 130.224485 , 130.2031475]),
 array([20.405255 , 20.3988525, 20.39051  , 20.38383  , 20.374465 ,
        20.36369  , 20.3511225, 20.3366675, 20.3186475, 20.290515 ]))

In [10]:
profilers[0].lon[2:10], profilers[0].lat[2:10]

(array([130.27472  , 130.2692775, 130.2517475, 130.240425 , 130.23472  ,
        130.22581  , 130.2234525, 130.2253425]),
 array([20.405255 , 20.3988525, 20.39051  , 20.38383  , 20.374465 ,
        20.36369  , 20.3511225, 20.3366675]))

In [13]:
profilers[0]

SprayData object for ARCTERX-Leg2
  Mission ID: 25203301
  Number of profiles: 310
  Time range: 2025-02-03 01:55:07.999998093 to 2025-04-10 23:52:25.249999762
  In field? True  ADCP on? True  Variables:
    depth: (100,)
    time: (310,)
    lat: (310,)
    lon: (310,)
    distE: (310,)
    distN: (310,)
    s: (310, 100)
    t: (310, 100)
    udop: (310, 100)
    vdop: (310, 100)

In [17]:
ctd['ctd'].keys()

dict_keys(['y0', 'y1', 'x0', 'x1', 'time0', 'time1', 'depthmin', 'missions', 'depth', 'missid', 'time', 'lon', 'lat', 'dist', 'offset', 'timeu', 'lonu', 'latu', 'distu', 'offsetu', 'u', 'v', 't', 's', 'udop', 'vdop'])

In [15]:
ctd['ctd']['missions']

['25203301', '25203801', '25204501', 'sg171', 'sg196', 'sg528', 'osu685']

In [22]:
np.sum(ctd['ctd']['missid'] == 1)

np.int64(306)